# Generated by Django 3.2 on 2022-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220501_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.TextField(blank=True, verbose_name='title'),
        ),
    ]
