# Generated by Django 3.2 on 2022-05-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_filmwork_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
    ]
