# Generated by Django 3.2 on 2022-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20220508_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
    ]
